/**
 * Provider registry, endpoint resolution, and forwarding helpers.
 *
 * @packageDocumentation
 */

export * from './registry.js';
export {
  forwardOpenAiCompatible,
  forwardAzureFoundryLegacy,
  buildChatCompletionsUrl,
  type ChatRequestBody,
} from './shared.js';
export * from './ollama.js';
export {
  forwardToDevin,
  DEVIN_DEFAULTS,
  devinAuthHeaders,
  buildDevinUrl,
  buildDevinOrgUrl,
  buildPaginationQuery,
  mapDevinError,
  devinSelf,
  devinListSessions,
  devinCreateSession,
  devinGetSession,
  devinTerminateSession,
  devinSendSessionMessage,
  devinListSessionMessages,
  devinArchiveSession,
  devinGetSessionTags,
  devinAppendSessionTags,
  devinReplaceSessionTags,
  devinGetPrReview,
  devinTriggerPrReview,
  devinListNotes,
  devinCreateNote,
  devinGetNote,
  devinUpdateNote,
  devinDeleteNote,
  devinKnowledgeFolders,
  devinListPlaybooks,
  devinCreatePlaybook,
  devinGetPlaybook,
  devinUpdatePlaybook,
  devinDeletePlaybook,
  devinListSecrets,
  devinCreateSecret,
  devinDeleteSecret,
  devinListRepositories,
  devinListIndexedRepos,
  devinIndexRepository,
  devinRemoveRepository,
  devinRepoIndexingStatus,
  devinListSchedules,
  devinCreateSchedule,
  devinGetSchedule,
  devinUpdateSchedule,
  devinDeleteSchedule,
  devinMetricsUsageOrg,
  devinMetricsSessions,
  devinMetricsPrs,
  devinMetricsSearches,
  devinMetricsActiveUsers,
  devinMetricsDau,
  devinMetricsWau,
  devinMetricsMau,
  devinConsumptionDaily,
  devinConsumptionDailyUser,
  devinConsumptionDailySession,
  devinConsumptionDailyServiceUser,
  type DevinProviderConfig,
  type DevinPaginatedResponse,
  type DevinPaginationOpts,
} from './devin.js';
export {
  FOUNDRY_DEFAULTS,
  isFoundrySdkMode,
  resolveProjectEndpoint,
  createFoundryClient,
  mapFoundryError,
  forwardAzureFoundry,
  forwardToFoundryChat,
  forwardToFoundryChatStream,
  forwardToFoundryResponses,
  foundryPing,
  foundryListDeployments,
  foundryGetDeployment,
  foundryListConnections,
  foundryGetConnection,
  foundryGetConnectionWithCredentials,
  foundryGetDefaultConnection,
  foundryListDatasets,
  foundryListDatasetVersions,
  foundryGetDataset,
  foundryDeleteDataset,
  foundryUploadDatasetFile,
  foundryListIndexes,
  foundryGetIndex,
  foundryCreateOrUpdateIndex,
  foundryListAgents,
  foundryCreateAgentVersion,
  foundryGetAgentVersion,
  foundryDeleteAgentVersion,
  foundryCreateConversation,
  foundryGetConversation,
  foundryDeleteConversation,
  type AzureFoundryProviderConfig,
  type FoundryForwardContext,
} from './azure-foundry.js';
export {
  DEEPSEEK_DEFAULTS,
  DEEPSEEK_MODELS,
  DEEPSEEK_LEGACY_ALIASES,
  resolveDeepSeekModel,
  isPrefixCompletion,
  isThinkingModel,
  mapDeepSeekUsage,
  mapDeepSeekError,
  forwardToDeepSeek,
  forwardToDeepSeekStream,
  getDeepSeekBalance,
  listDeepSeekModels,
  type DeepSeekUsage,
  type NormalizedDeepSeekUsage,
} from './deepseek.js';
export {
  ZAI_DEFAULTS,
  ZAI_MODELS,
  isZaiThinkingCapable,
  isZaiVisionModel,
  mapZaiUsage,
  mapZaiError,
  forwardToZaiChat,
  forwardToZaiChatStream,
  getZaiAsyncResult,
  buildZaiPaasUrl,
  buildZaiV1Url,
  type ZaiUsage,
  type NormalizedZaiUsage,
} from './zai.js';
export {
  OLLAMA_CLOUD_DEFAULTS,
  OLLAMA_CLOUD_MODELS,
  stripCloudSuffix,
  isOllamaCloudModel,
  supportsThink,
  mapOllamaUsage,
  mapOllamaCloudError,
  forwardToOllamaCloudChat,
  forwardToOllamaCloudChatStream,
  ollamaCloudGenerate,
  ollamaCloudEmbed,
  ollamaCloudListModels,
  ollamaCloudListRunning,
  ollamaCloudShowModel,
  ollamaCloudVersion,
  ollamaCloudAnthropicMessages,
  buildOllamaCloudOpenAiUrl,
  buildOllamaCloudNativeUrl,
  type OllamaUsage,
  type NormalizedOllamaUsage,
} from './ollama-cloud.js';
export {
  NVIDIA_DEFAULTS,
  NVIDIA_MODELS,
  isNvidiaThinkingModel,
  isNvidiaVisionModel,
  mapNvidiaUsage,
  mapNvidiaError,
  forwardToNvidiaChat,
  forwardToNvidiaChatStream,
  nvidiaEmbed,
  nvidiaRank,
  nvidiaListModels,
  buildNvidiaChatUrl,
  type NvidiaUsage,
} from './nvidia.js';
export {
  CURSOR_DEFAULTS,
  CURSOR_ALLOWED_PREFIXES,
  cursorBasicAuthHeaders,
  buildCursorUrl,
  isAllowedCursorPath,
  mapCursorError,
  cursorRequest,
  cursorTeamMembers,
  cursorAnalyticsDau,
  cursorAiCodeCommits,
  cursorAiCodeChanges,
  type CursorProviderConfig,
  type CursorRequestOpts,
} from './cursor.js';
export {
  COPILOT_DEFAULTS,
  resolveCopilotToken,
  resolveCopilotTokenFromBearer,
  mapCopilotError,
  extractCopilotPrompt,
  forwardToCopilotChat,
  forwardToCopilotChatStream,
  copilotPing,
  copilotListSessions,
  copilotCreateSession,
  copilotResumeSession,
  copilotDeleteSession,
  copilotSendAndWait,
  copilotGetEvents,
  copilotAbort,
  type CopilotProviderConfig,
} from './copilot.js';
export {
  KIMI_DEFAULTS,
  resolveKimiApiKey,
  resolveKimiApiKeyFromBearer,
  resolveKimiBaseUrl,
  mapKimiUsage,
  mapKimiError,
  forwardToKimiChat,
  forwardToKimiChatStream,
  kimiGetBalance,
  kimiListModels,
  kimiEstimateTokens,
  kimiUploadFile,
  kimiListFiles,
  kimiGetFile,
  kimiDeleteFile,
  kimiGetFileContent,
  kimiPing,
  type KimiProviderConfig,
  type KimiRegion,
} from './kimi.js';
export {
  KIMI_AGENT_DEFAULTS,
  isKimiCliAvailable,
  mapKimiAgentError,
  isWireEvent,
  extractTextDeltaFromEvent,
  extractTokenUsageFromEvent,
  tokenUsageToOpenAi,
  streamEventToSseChunk,
  getOrCreateKimiAgentSession,
  extractKimiAgentPrompt,
  kimiAgentPing,
  kimiAgentGetConfig,
  kimiAgentListSessions,
  kimiAgentCreateSession,
  kimiAgentGetSessionEvents,
  kimiAgentDeleteSession,
  kimiAgentSaveDefaultModel,
  kimiAgentAuthMcp,
  kimiAgentResetAuthMcp,
  kimiAgentTestMcp,
  kimiAgentSessionPrompt,
  getActiveKimiTurn,
  forwardToKimiAgentChat,
  forwardToKimiAgentChatStream,
  type KimiAgentProviderConfig,
} from './kimi-agent.js';
export {
  QWEN_DEFAULTS,
  resolveQwenApiKey,
  resolveQwenApiKeyFromBearer,
  resolveQwenBaseUrl,
  isQwenThinkingModel,
  applyQwenThinkingDefaults,
  mapQwenUsage,
  mapQwenError,
  forwardToQwenChat,
  forwardToQwenChatStream,
  qwenListModels,
  qwenPing,
  type QwenProviderConfig,
  type QwenRegion,
} from './qwen.js';
export {
  QWEN_AGENT_DEFAULTS,
  buildQwenQueryOptions,
  mapQwenAgentError,
  extractTextFromContentBlocks,
  extractTextFromAssistantMessage,
  extractTextDeltaFromPartialMessage,
  usageToOpenAi,
  partialMessageToSseChunk,
  extractQwenAgentPrompt,
  forwardToQwenAgentChat,
  forwardToQwenAgentChatStream,
  getActiveQwenQuery,
  qwenAgentPing,
  qwenAgentStartSession,
  qwenAgentSessionPrompt,
  qwenAgentCloseSession,
  type QwenAgentProviderConfig,
} from './qwen-agent.js';
export {
  OPENROUTER_DEFAULTS,
  resolveOpenRouterToken,
  mapOpenRouterError,
  mapOpenRouterUsage,
  toOpenAiChatCompletion,
  forwardToOpenRouterChat,
  forwardToOpenRouterChatStream,
  openRouterListModels,
  openRouterModelsCount,
  openRouterGetModel,
  openRouterGetCredits,
  openRouterGetGeneration,
  openRouterListGenerationContent,
  openRouterCreateEmbeddings,
  openRouterListEmbeddingModels,
  openRouterListProviders,
  parseOpenRouterModelSlug,
  type OpenRouterProviderConfig,
} from './openrouter.js';
export {
  OPENCODE_ZEN_DEFAULTS,
  parseOpencodeModelName,
  resolveOpencodeProtocol,
  buildOpencodeUpstreamUrl,
  resolveOpencodeZenToken,
  mapOpencodeError,
  mapOpencodeUsage,
  forwardToOpencodeZenChat,
  forwardToOpencodeZenChatStream,
  forwardToOpencodeZenMessages,
  forwardToOpencodeZenResponses,
  listOpencodeZenModels,
  type OpencodeZenProviderConfig,
} from './opencode-zen.js';
export {
  OPENCODE_GO_DEFAULTS,
  resolveOpencodeGoToken,
  forwardToOpencodeGoChat,
  forwardToOpencodeGoChatStream,
  forwardToOpencodeGoMessages,
  forwardToOpencodeGoResponses,
  listOpencodeGoModels,
  type OpencodeGoProviderConfig,
} from './opencode-go.js';
export {
  OPENCODE_SERVER_DEFAULTS,
  createOpencodeServerClient,
  opencodePing,
  opencodeGetConfig,
  opencodeGetProviders,
  opencodeListProjects,
  opencodeCurrentProject,
  opencodeListSessions,
  opencodeCreateSession,
  opencodeGetSession,
  opencodeDeleteSession,
  opencodeSessionPrompt,
  opencodeSessionAbort,
  opencodeSessionMessages,
  opencodeFindText,
  opencodeFindFiles,
  opencodeFileRead,
  opencodeSubscribeEvents,
  type OpencodeServerProviderConfig,
} from './opencode.js';
export {
  resolveGoogleApiKey,
  resolveGoogleApiKeyFromBearer,
  mapGoogleError,
  GOOGLE_API_DEFAULTS,
} from './google-shared.js';
export {
  GOOGLE_ADK_DEFAULTS,
  adkPing,
  adkCreateSession,
  adkListSessions,
  adkGetSession,
  adkDeleteSession,
  adkRunSession,
  adkRunEphemeral,
  forwardToGoogleAdkChat,
  forwardToGoogleAdkChatStream,
  type GoogleAdkProviderConfig,
} from './google-adk.js';
export {
  ANTIGRAVITY_DEFAULTS,
  antigravityCreateInteraction,
  antigravityGetInteraction,
  antigravityCancelInteraction,
  forwardToAntigravityChat,
  forwardToAntigravityChatStream,
  type AntigravityProviderConfig,
} from './antigravity.js';
export {
  AGY_DEFAULTS,
  forwardToAgyChat,
  forwardToAgyChatStream,
  type AgyProviderConfig,
} from './agy.js';
